### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by beenotung** [esimov/caire#22]
Failed when scaling a jpg image of 204x383 to png of 408x766.
Tried to `caire -in in.jpg -out out.jpg -square`, that was fine.

```
$ caire -in in.jpg -out out.png -width=408 -height=766
Processing... -panic: runtime error: index out of range

goroutine 1 [running]:
github.com/esimov/caire.(*Carver).get(...)
	/home/beenotung/goroot/src/github.com/esimov/caire/carver.go:49
github.com/esimov/caire.(*Carver).ComputeSeams(0xc420b9c0c0, 0xc420058800, 0xc42001c1e0, 0xc420a6d600, 0x198, 0x198)
	/home/beenotung/goroot/src/github.com/esimov/caire/carver.go:109 +0x6e9
github.com/esimov/caire.(*Processor).Resize.func1()
	/home/beenotung/goroot/src/github.com/esimov/caire/process.go:66 +0x116
github.com/esimov/caire.(*Processor).Resize(0xc42001c1e0, 0xc420058800, 0xc4200e0080, 0xc420058340, 0xffffffffffffffff, 0xc4201d8000)
	/home/beenotung/goroot/src/github.com/esimov/caire/process.go:122 +0x51f
github.com/esimov/caire.Resize(0x5ac2c0, 0xc42001c1e0, 0xc420058340, 0xc4200e0080, 0x51cdb0, 0x4, 0x0)
	/home/beenotung/goroot/src/github.com/esimov/caire/process.go:35 +0x3b
github.com/esimov/caire.(*Processor).Process(0xc42001c1e0, 0x5ac4c0, 0xc42000c080, 0x5ac500, 0xc42000c088, 0x0, 0x0)
	/home/beenotung/goroot/src/github.com/esimov/caire/process.go:138 +0x7e
main.main()
	/home/beenotung/goroot/src/github.com/esimov/caire/cmd/caire/main.go:121 +0x54c
```

**Comment by esimov** [comment]
Thanks, i will take a look.

**Comment by esimov** [comment]
Issue fixed.
