### ISSUE TITLE
index out of range when scaling up

### ISSUE THREAD

**Issue by Southclaws** [esimov/caire#3]
I'm playing around with this as a library rather than a command-line utility, I wanted to do stuff in-memory without files and unfortunately `Process` doesn't take an `io.Writer` (PR incoming!) so for now, I simply copied this code:

```go
	src, _, err := image.Decode(file)
	if err != nil {
		return nil, err
	}
	img := imgToNRGBA(src)
	res, err := Resize(p, img)
	if err != nil {
		return nil, err
	}
```

Now this works fine going down in size but when going up in size, this happens:

```
panic: runtime error: index out of range

goroutine 1 [running]:
	/Users/southclaws/go/src/github.com/esimov/caire/carver.go:108 +0xb4b
github.com/esimov/caire.(*Processor).Resize.func1()
	/Users/southclaws/go/src/github.com/esimov/caire/process.go:65 +0x15d
github.com/esimov/caire.(*Processor).Resize(0xc420094090, 0xc420058840, 0x0, 0x0, 0x0, 0x0)
	/Users/southclaws/go/src/github.com/esimov/caire/process.go:115 +0x8c4
github.com/esimov/caire.Resize(0x11cd280, 0xc420094090, 0xc42008a140, 0x0, 0x0, 0x0, 0x0)
	/Users/southclaws/go/src/github.com/esimov/caire/process.go:35 +0x9c
main.resize(0x11cd480, 0xc420096070, 0x11cd4c0, 0xc420096078, 0x3fe999999999999a, 0x3fe0000000000000, 0x0, 0x0)
	/Users/southclaws/Desktop/untitled folder/main.go:65 +0xabc
main.main()
	/Users/southclaws/Desktop/untitled folder/main.go:27 +0x2ae
```

**Comment by esimov** [comment]
Normally this shouldn't happen. Can you show me command you tried?

**Comment by Southclaws** [comment]
I can't seem to reproduce this now, I was hacking around and forgot exactly what I did... sorry!
